### ISSUE TITLE
老哥，你把年龄隐去了，前妻表上好像还有年龄

### ISSUE THREAD

**Issue by songyang1995** [reed-chan/Random-waifu-generater#26]
给出来的结果这样的，肤色和发型中间 th上没年龄，但数据里面有

身高 | 体重 | CUP | 肤色 | 发型 | 发色 | 瞳色 | 属性 | 性格
-- | -- | -- | -- | -- | -- | -- | -- | --
166 | 54 | A | 正常 | 19 | 麻花辫 | #e7c898 | #89d7f2 | 文学少女 | 拜金
172 | 62 | C | 黑妹 | 17 | 低马尾 | #4a70ad | #a3c523 | 杀手 | 弱气
165 | 56 | G | 正常 | 24 | 姬发式 | #ef33a9 | #3efed0 | 圣女 | 弱气
170 | 59 | E | 洁白 | 23 | 中长发 | #3c1810 | #29f566 | 天降系 | 毒舌
169 | 61 | C | 正常 | 19 | 麻花辫 | #0b6e65 | #dcb7d0 | 姐姐 | 中二

**Comment by reed-chan** [comment]
😭改好了

**Comment by songyang1995** [comment]
稳~
