### ISSUE TITLE
上热搜了哥，只是这waifu是日式读法吗

### ISSUE THREAD

**Issue by kiritokun07** [reed-chan/Random-waifu-generater#6]

**Comment by kiritokun07** [comment]
再来个字典随机生成老婆名字就更好了

**Comment by user670** [comment]
是的。英语圈用waifu（而非wife）表示二次元“老婆”。还有……husbando（这拼写有点四不像）表示二次元“老公”

**Comment by kiritokun07** [comment]
> 是的。英语圈用waifu（而非wife）表示二次元“老婆”。还有……husbando（这拼写有点四不像）表示二次元“老公”
